/**
 * Event Maintenance Script
 * Run this script periodically (e.g., via cron) to:
 * - Update event statuses based on time
 * - Archive old completed events
 * - Expire old event requests
 * 
 * Prerequisites:
 * 1. Build the TypeScript code: npm run build
 * 2. Ensure environment variables are set (DATABASE_URL, etc.)
 * 
 * Usage:
 * node scripts/eventMaintenance.js
 * 
 * Cron example (daily at 2 AM):
 * 0 2 * * * cd /path/to/Teamly && node scripts/eventMaintenance.js >> logs/maintenance.log 2>&1
 * 
 * Note: This script imports from dist/backend/utils/eventStatusUpdater.js
 * which is generated by TypeScript compilation. If you modify the TypeScript
 * source, make sure to rebuild before running this script.
 */

// Import from the compiled TypeScript utilities
// Path is relative to project root: dist/backend/utils/eventStatusUpdater.js
const { updateEventStatuses, archiveOldEvents, expireOldEventRequests } = require('../dist/backend/utils/eventStatusUpdater');
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  try {
    console.log('=== Event Maintenance Job Started ===');
    console.log('Timestamp:', new Date().toISOString());
    
    // Use the utility functions from the compiled TypeScript
    const statusResult = await updateEventStatuses();
    const archiveResult = await archiveOldEvents(30);
    const expireResult = await expireOldEventRequests();

    console.log('=== Event Maintenance Job Completed ===');
    console.log('Summary:');
    console.log(`  - Event statuses updated: ${statusResult.updated}`);
    console.log(`  - Events archived: ${archiveResult.archived}`);
    console.log(`  - Event requests expired: ${expireResult.expired}`);
    console.log(`  - Total errors: ${statusResult.errors + archiveResult.errors + expireResult.errors}`);
    
    const totalErrors = statusResult.errors + archiveResult.errors + expireResult.errors;
    if (totalErrors > 0) {
      console.error('WARNING: Some operations failed. Check logs for details.');
      process.exit(1);
    }
    
    process.exit(0);
  } catch (error) {
    console.error('FATAL ERROR during event maintenance:', error);
    console.error('Make sure to run `npm run build` before executing this script');
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
